name: Publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11'
      - run: npm i
      - run: |
          npm run build
          cp README.md packages/playground/
      - run: |
          TAG='latest'
          PRERELEASE=false

          if [[ $GITHUB_REF_NAME =~ 'alpha' || $GITHUB_REF_NAME =~ 'beta' || $GITHUB_REF_NAME =~ 'rc' ]]; then
            TAG='next'
            PRERELEASE=true
          fi

          echo "NPM_TAG=$PRERELEASE" >> $GITHUB_ENV
          echo "IS_PRERELEASE=$PRERELEASE" >> $GITHUB_ENV
      - uses: JS-DevTools/npm-publish@v3
        with:
          provenance: true
          package: packages/playground/
          tag: ${{ env.NPM_TAG }}
          token: ${{ secrets.NPM_TOKEN }}
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: v${{ github.ref_name }}
          body: Please refer to [CHANGELOG.md](https://github.com/studiometa/playground/blob/${{ github.ref_name }}/CHANGELOG.md) for details.
          draft: false
          prerelease: ${{ env.IS_PRERELEASE }}
